### ISSUE TITLE
Need a help on validating the Login Page 

### ISSUE THREAD

**Issue by Rashmi-Nuviso** [A9T9/SeeShell#1]
Hi 
Can any body help here validating the Login page for my web application ?

When i try to send the username password in the login page the password sent by the Kantu while playing the testcase is blank .

Can any of you suggest me  how do i Make the password persist during the TC palyout .

my testcase looks like this 
{
  "CreationDate": "2017-11-7",
  "Commands": [
    {
      "Command": "open",
      "Target": "http://10.48.114.31:8080/ui/#/?_k=q3phjo",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "name=username",
      "Value": ""
    },
    {
      "Command": "type",
      "Target": "name=username",
      "Value": "test@abc.com"
    },
    {
      "Command": "click",
      "Target": "name=password",
      "Value": ""
    },
    {
      "Command": "type",
      "Target": "name=password",         
      "Value": "test"                                ----> _this value is not  keyed in properly and sent as blank . Need help here_ 
    },
    {
      "Command": "click",
      "Target": "css=label.fa.fa-arrow-right",
      "Value": ""
    },
    {
      "Command": "waitForPageToLoad",
      "Target": "",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "//*[@id=\"root\"]/div/div/div[2]/div[3]/div[1]",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "//*[@id=\"root\"]/div/div/div[2]/div[3]/div[2]",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "//*[@id=\"root\"]/div/div/div[2]/div[3]/div[4]",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "//*[@id=\"root\"]/div/div/div[2]/div[3]/div[5]",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "css=i.fa.fa-user",
      "Value": ""
    },
    {
      "Command": "click",
      "Target": "//*[@id=\"root\"]/div/div/div[2]/div[2]/ul/li/div",
      "Value": ""
    }
  ]
}

**Comment by A9T9** [comment]
Please ask question of this kind in our new user forum at https://forum.a9t9.com/
