### ISSUE TITLE
windows application ( keep using old script even after the edit )

### ISSUE THREAD

**Issue by ghost** [A9T9/SeeShell#2]
for the windows application, if you 
- create a script 
- run it in the loop 
-  stop it.
- edit it. 
- save changes. 
- try to run it again in the loop it will run the old one before the edit. 
- you have to run it 1 time in a single run then the loop will get the new script or close the app and open it again

**Comment by A9T9** [comment]
Please ask question of this kind in our user forum at https://forum.a9t9.com/
